### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by brannondorsey** [ekQ/dopelearning#1]
Great paper! Any chance you could make the dataset publicly available?

**Comment by ekQ** [comment]
Thanks. Could you specify which dataset you mean?

**Comment by brannondorsey** [comment]
Apologies for lack of clarity. From the paper:
> We assume that we have access to a large repository of rap-song lyrics.  In this pa-
per,  we  use  a  dataset  containing  over  half  a  million  lines from  lyrics  of  104  different  rap  artists.

**Comment by ekQ** [comment]
Thanks for the clarification. Unfortunately, I'm unable to share that data due to lyric copyright issues. You might be able to collect a similar (and more up-to-date) dataset from some lyrics website, like ohhla.com.

**Comment by brannondorsey** [comment]
Ah, I understand. For folks that may be interested in finding a similar dataset in the future, I've provided instructions for scraping the Original Hip-Hop Lyrics Archive [here](https://github.com/brannondorsey/ml4music-workshop/tree/master/data/lyrics/data/ohhla_lyrics). I was able to scrape lyrics for around ~4,800 songs (hint: input.txt).
